# Generated by Django 4.0.4 on 2022-07-12 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CursosDisponiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=150)),
                ('professor', models.CharField(max_length=50)),
                ('contato_professor', models.CharField(blank=True, max_length=30, null=True)),
                ('data_curso', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='CursosInscritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cursoinscrito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.cursosdisponiveis')),
                ('nome_usuarioinscrito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Cursos Inscrito',
            },
        ),
    ]
