# Generated by Django 4.0.4 on 2022-07-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AlterField(
            model_name='cursosdisponiveis',
            name='data_curso',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='CursosInscritos',
        ),
    ]
