# Generated by Django 4.0.4 on 2022-07-19 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('cursos', '0003_remove_cursosdisponiveis_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursosInscritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.CharField(choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Ótimo')], max_length=1)),
                ('curso', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.cursosdisponiveis')),
                ('user', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
        ),
    ]
