# Generated by Django 4.0.4 on 2022-07-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_cursosinscritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosinscritos',
            name='avaliacao',
            field=models.CharField(blank=True, choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Ótimo')], max_length=1, null=True),
        ),
    ]
