# Generated by Django 4.0.4 on 2022-07-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_cursosinscritos_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosinscritos',
            name='comentario',
            field=models.TextField(blank=b'I01\n', max_length=35, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
